name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Build plugin
        run: |
          npm install --force
          npm run build

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-path: |
            dist/main.js
            manifest.json
            dist/styles.css

      # - name: Generate release notes from changelog
      #   id: notes
      #   run: |
      #     node ./getChangelogEntry.mjs > RELEASE_NOTES.md
      #     echo "file=RELEASE_NOTES.md" >> "$GITHUB_OUTPUT"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            dist/main.js manifest.json dist/styles.css
